In [ ]:
import numpy as np
import os
import pandas as pd
import tensorflow.keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split

In [ ]:
df=pd.read_csv("/content/sample_data/HipparcosPeriodic.csv")

In [ ]:
display(df)

hip cat  type  p2pScatterOnDetrendedTS  ...  VI_Color    JmK    JmH    HmK
0     100033   P   LPV                 0.324372  ...      3.00  1.372  0.841  0.531
1     100048   P   LPV                 0.436983  ...      2.82  1.181  0.530  0.651
2     100107   P    EB                 0.021372  ...      0.52  0.261  0.200  0.061
3     100113   P   LPV                 0.024881  ...      3.01  2.121  1.290  0.831
4     100135   P    EB                 0.046822  ...      0.66  0.294  0.229  0.065
...      ...  ..   ...                      ...  ...       ...    ...    ...    ...
1656   99765   P   CWA                 0.094059  ...      0.43  0.510  0.458  0.052
1657   99802   P   LPV                 0.188887  ...      3.56  1.526  0.906  0.620
1658   99887   P  DCEP                 0.012961  ...      1.10  0.882  0.633  0.249
1659    9990   P  ACYG                 0.000163  ...      0.85  0.416 -0.033  0.449
1660   99927   P   ACV                 0.000271  ...     -0.04 -0.092 -0.095  0.003

[1661 rows x 45 columns]

Variables that we need to select are

attr.to.choose= c("LogPeriod","JmK","Raw_PercentileRange10", "JmH","VI_Color","Raw_WeightedSkewness",   
                  "BV_Color","A11","LogAmplitude","Raw_WeightedStdDev",
                  "nonQsoVar","logA12_A11","qsoVar","WstetsonK","PH12",
                  "p2pScatterOnDetrendedTS")

In [ ]:
attr_to_choose=["LogPeriod","JmK","Raw_PercentileRange10", "JmH","VI_Color","Raw_WeightedSkewness",
"BV_Color","A11","LogAmplitude","Raw_WeightedStdDev", "nonQsoVar","logA12_A11","qsoVar","WstetsonK","PH12", "p2pScatterOnDetrendedTS"]

In [ ]:
#Convert to explanatory and response variables
x=df[attr_to_choose].values
dummies = pd.get_dummies(df['type']) # Classification
types = dummies.columns
y = dummies.values
display(y)



array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [ ]:
display(x)
display(y)

array([[ 2.48148606e+00,  1.37200000e+00, -1.99560000e+00, ...,
         9.24545475e-01,  1.57079633e+00,  3.24371721e-01],
       [ 2.30103000e+00,  1.18100000e+00, -1.05040000e+00, ...,
         9.39285577e-01,  1.57079633e+00,  4.36982819e-01],
       [-5.74563676e-01,  2.61000000e-01, -9.39000000e-02, ...,
         8.41971033e-01, -1.52257629e+00,  2.13716252e-02],
       ...,
       [ 8.27105302e-01,  8.82000000e-01, -1.98900000e-01, ...,
         9.11443968e-01,  3.10600844e+00,  1.29606783e-02],
       [ 4.29573822e-01,  4.16000000e-01, -2.08500000e-02, ...,
         7.92173723e-01,  1.57079633e+00,  1.62766379e-04],
       [ 1.22621356e+00, -9.20000000e-02, -3.25500000e-02, ...,
         8.07344853e-01,  2.02667644e+00,  2.70930480e-04]])

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [ ]:
import pandas as pd
import os
import numpy as np
from sklearn import metrics
from sklearn.model_selection import StratifiedKFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras import regularizers

# np.argmax(pred,axis=1)
# Cross-validate
# Use for StratifiedKFold classification
kf = StratifiedKFold(5, shuffle=True, random_state=42) 
    
oos_y = []
oos_pred = []
fold = 0

# Must specify y StratifiedKFold for
for train, test in kf.split(x,df['type']):  
    fold+=1
    print(f"Fold #{fold}")
        
    x_train = x[train]
    y_train = y[train]
    x_test = x[test]
    y_test = y[test]
    
    model = Sequential()
    model.add(Dense(32, input_dim=x.shape[1], 
                    activation='relu',
                    #kernel_regularizer=regularizers.l1_l2(l1=1e-5, l2=1e-4),
                    activity_regularizer=regularizers.l1(1e-2))) # Hidden 1
    model.add(Dense(96, activation='relu',
                    activity_regularizer=regularizers.l1(1e-2))) # Hidden 2
    model.add(Dense(units=df['type'].nunique(),activation="softmax")) # Output
    model.compile(loss='categorical_crossentropy', optimizer='adam')

    model.fit(x_train,y_train,validation_data=(x_test,y_test),verbose=0,epochs=500)
    
    pred = model.predict(x_test)
    
    oos_y.append(y_test)
    # raw probabilities to chosen class (highest probability)
    pred = np.argmax(pred,axis=1) 
    oos_pred.append(pred)  

    # Measure this fold's accuracy
    y_compare = np.argmax(y_test,axis=1) # For accuracy calculation
    score = metrics.accuracy_score(y_compare, pred)
    print(f"Fold score (accuracy): {score}")

# Build the oos prediction list and calculate the error.
oos_y = np.concatenate(oos_y)
oos_pred = np.concatenate(oos_pred)
oos_y_compare = np.argmax(oos_y,axis=1) # For accuracy calculation

score = metrics.accuracy_score(oos_y_compare, oos_pred)
print(f"Final score (accuracy): {score}")    
    
# Write the cross-validated prediction
oos_y = pd.DataFrame(oos_y)
oos_pred = pd.DataFrame(oos_pred)
oosDF = pd.concat( [df, oos_y, oos_pred],axis=1 )

Fold #1
Fold score (accuracy): 0.7207207207207207
Fold #2
Fold score (accuracy): 0.7650602409638554
Fold #3
Fold score (accuracy): 0.7439759036144579
Fold #4
Fold score (accuracy): 0.7530120481927711
Fold #5
Fold score (accuracy): 0.7228915662650602
Final score (accuracy): 0.741119807344973


I tried to run the code several times and found that the Fold #2 consistently gives higher score. So it is clear that there is an outlier in Fold #2, which might be causing this. We could look into it, to see if we want to keep the outlier or at the very least we want to know about it.

# Drop Out for Keras to Decrease Overfitting 

In [ ]:
import pandas as pd
from scipy.stats import zscore

# Read the data set
df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/jh-simple-dataset.csv",
    na_values=['NA','?'])

# Generate dummies for job
df = pd.concat([df,pd.get_dummies(df['job'],prefix="job")],axis=1)
df.drop('job', axis=1, inplace=True)

# Generate dummies for area
df = pd.concat([df,pd.get_dummies(df['area'],prefix="area")],axis=1)
df.drop('area', axis=1, inplace=True)

# Missing values for income
med = df['income'].median()
df['income'] = df['income'].fillna(med)

# Standardize ranges
df['income'] = zscore(df['income'])
df['aspect'] = zscore(df['aspect'])
df['save_rate'] = zscore(df['save_rate'])
df['age'] = zscore(df['age'])
df['subscriptions'] = zscore(df['subscriptions'])

# Convert to numpy - Classification
x_columns = df.columns.drop('product').drop('id')
x = df[x_columns].values
dummies = pd.get_dummies(df['product']) # Classification
products = dummies.columns
y = dummies.values


In [ ]:
########################################
# Keras with dropout for Classification
########################################

import pandas as pd
import os
import numpy as np
from sklearn import metrics
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Dropout
from tensorflow.keras import regularizers


kf=KFold(5,shuffle=True,random_state=42)
oos_y=[]
oos_pred=[]
fold=0

for train, test in kf.split(x):
    fold+=1
    print(f"Fold #{fold}")

    x_train=x[train]
    y_train=y[train]
    x_test=x[test]
    y_test=y[test]

    model = Sequential()
    model.add(Dense(50, input_dim=x.shape[1], activation='relu')) # Hidden 1
    model.add(Dropout(0.1))
    model.add(Dense(25, activation='relu', \
                activity_regularizer=regularizers.l1(1e-4))) # Hidden 2
    # Usually do not add dropout after final hidden layer
    #model.add(Dropout(0.5)) 
    model.add(Dense(y.shape[1],activation='softmax')) # Output
    model.compile(loss='categorical_crossentropy', optimizer='adam')

    model.fit(x_train,y_train,validation_data=(x_test,y_test),\
              verbose=0,epochs=500)
    
    pred = model.predict(x_test)
    
    oos_y.append(y_test)
    # raw probabilities to chosen class (highest probability)
    pred = np.argmax(pred,axis=1) 
    oos_pred.append(pred)        

    # Measure this fold's accuracy
    y_compare = np.argmax(y_test,axis=1) # For accuracy calculation
    score = metrics.accuracy_score(y_compare, pred)
    print(f"Fold score (accuracy): {score}")


# Build the oos prediction list and calculate the error.
oos_y = np.concatenate(oos_y)
oos_pred = np.concatenate(oos_pred)
oos_y_compare = np.argmax(oos_y,axis=1) # For accuracy calculation

score = metrics.accuracy_score(oos_y_compare, oos_pred)
print(f"Final score (accuracy): {score}")    
    
# Write the cross-validated prediction
oos_y = pd.DataFrame(oos_y)
oos_pred = pd.DataFrame(oos_pred)
oosDF = pd.concat( [df, oos_y, oos_pred],axis=1 )
#oosDF.to_csv(filename_write,index=False)

Fold #1
Fold score (accuracy): 0.655
Fold #2
Fold score (accuracy): 0.6975
Fold #3
Fold score (accuracy): 0.7075
Fold #4
Fold score (accuracy): 0.7025
Fold #5
Fold score (accuracy): 0.655
Final score (accuracy): 0.6835


It seems that the dropout regularization seems to decrease the overall accuracy